/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin.login'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as AuthenticatedVentesRouteImport } from './routes/_authenticated/ventes'
import { Route as AuthenticatedSuperAdminRouteImport } from './routes/_authenticated/super-admin'
import { Route as AuthenticatedStocksRouteImport } from './routes/_authenticated/stocks'
import { Route as AuthenticatedProduitsRouteImport } from './routes/_authenticated/produits'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedEmployesRouteImport } from './routes/_authenticated/employes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConformiteRouteImport } from './routes/_authenticated/conformite'
import { Route as AuthenticatedComptabiliteRouteImport } from './routes/_authenticated/comptabilite'
import { Route as AuthenticatedCaisseRouteImport } from './routes/_authenticated/caisse'
import { Route as AuthenticatedSuperAdminIndexRouteImport } from './routes/_authenticated/super-admin.index'
import { Route as AuthenticatedSuperAdminMfaRouteImport } from './routes/_authenticated/super-admin.mfa'
import { Route as AuthenticatedSuperAdminLogsRouteImport } from './routes/_authenticated/super-admin.logs'
import { Route as AuthenticatedSuperAdminEntreprisesRouteImport } from './routes/_authenticated/super-admin.entreprises'
import { Route as AuthenticatedSuperAdminAdminsRouteImport } from './routes/_authenticated/super-admin.admins'
import { Route as AuthenticatedSuperAdminAbonnementsRouteImport } from './routes/_authenticated/super-admin.abonnements'
import { Route as AuthenticatedProduitsProductIdRouteImport } from './routes/_authenticated/produits.$productId'

const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentesRoute = AuthenticatedVentesRouteImport.update({
  id: '/ventes',
  path: '/ventes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminRoute = AuthenticatedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStocksRoute = AuthenticatedStocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProduitsRoute = AuthenticatedProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployesRoute = AuthenticatedEmployesRouteImport.update({
  id: '/employes',
  path: '/employes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConformiteRoute = AuthenticatedConformiteRouteImport.update({
  id: '/conformite',
  path: '/conformite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComptabiliteRoute =
  AuthenticatedComptabiliteRouteImport.update({
    id: '/comptabilite',
    path: '/comptabilite',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCaisseRoute = AuthenticatedCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperAdminIndexRoute =
  AuthenticatedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminMfaRoute =
  AuthenticatedSuperAdminMfaRouteImport.update({
    id: '/mfa',
    path: '/mfa',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminLogsRoute =
  AuthenticatedSuperAdminLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminEntreprisesRoute =
  AuthenticatedSuperAdminEntreprisesRouteImport.update({
    id: '/entreprises',
    path: '/entreprises',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAdminsRoute =
  AuthenticatedSuperAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedSuperAdminAbonnementsRoute =
  AuthenticatedSuperAdminAbonnementsRouteImport.update({
    id: '/abonnements',
    path: '/abonnements',
    getParentRoute: () => AuthenticatedSuperAdminRoute,
  } as any)
const AuthenticatedProduitsProductIdRoute =
  AuthenticatedProduitsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProduitsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/conformite': typeof AuthenticatedConformiteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employes': typeof AuthenticatedEmployesRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/produits': typeof AuthenticatedProduitsRouteWithChildren
  '/stocks': typeof AuthenticatedStocksRoute
  '/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/ventes': typeof AuthenticatedVentesRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/produits/$productId': typeof AuthenticatedProduitsProductIdRoute
  '/super-admin/abonnements': typeof AuthenticatedSuperAdminAbonnementsRoute
  '/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/super-admin/entreprises': typeof AuthenticatedSuperAdminEntreprisesRoute
  '/super-admin/logs': typeof AuthenticatedSuperAdminLogsRoute
  '/super-admin/mfa': typeof AuthenticatedSuperAdminMfaRoute
  '/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/caisse': typeof AuthenticatedCaisseRoute
  '/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/conformite': typeof AuthenticatedConformiteRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employes': typeof AuthenticatedEmployesRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/produits': typeof AuthenticatedProduitsRouteWithChildren
  '/stocks': typeof AuthenticatedStocksRoute
  '/ventes': typeof AuthenticatedVentesRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/produits/$productId': typeof AuthenticatedProduitsProductIdRoute
  '/super-admin/abonnements': typeof AuthenticatedSuperAdminAbonnementsRoute
  '/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/super-admin/entreprises': typeof AuthenticatedSuperAdminEntreprisesRoute
  '/super-admin/logs': typeof AuthenticatedSuperAdminLogsRoute
  '/super-admin/mfa': typeof AuthenticatedSuperAdminMfaRoute
  '/super-admin': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/_authenticated/caisse': typeof AuthenticatedCaisseRoute
  '/_authenticated/comptabilite': typeof AuthenticatedComptabiliteRoute
  '/_authenticated/conformite': typeof AuthenticatedConformiteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employes': typeof AuthenticatedEmployesRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/produits': typeof AuthenticatedProduitsRouteWithChildren
  '/_authenticated/stocks': typeof AuthenticatedStocksRoute
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteWithChildren
  '/_authenticated/ventes': typeof AuthenticatedVentesRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/_authenticated/produits/$productId': typeof AuthenticatedProduitsProductIdRoute
  '/_authenticated/super-admin/abonnements': typeof AuthenticatedSuperAdminAbonnementsRoute
  '/_authenticated/super-admin/admins': typeof AuthenticatedSuperAdminAdminsRoute
  '/_authenticated/super-admin/entreprises': typeof AuthenticatedSuperAdminEntreprisesRoute
  '/_authenticated/super-admin/logs': typeof AuthenticatedSuperAdminLogsRoute
  '/_authenticated/super-admin/mfa': typeof AuthenticatedSuperAdminMfaRoute
  '/_authenticated/super-admin/': typeof AuthenticatedSuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/login'
    | '/mentions-legales'
    | '/caisse'
    | '/comptabilite'
    | '/conformite'
    | '/dashboard'
    | '/employes'
    | '/parametres'
    | '/produits'
    | '/stocks'
    | '/super-admin'
    | '/ventes'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/produits/$productId'
    | '/super-admin/abonnements'
    | '/super-admin/admins'
    | '/super-admin/entreprises'
    | '/super-admin/logs'
    | '/super-admin/mfa'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialite'
    | '/login'
    | '/mentions-legales'
    | '/caisse'
    | '/comptabilite'
    | '/conformite'
    | '/dashboard'
    | '/employes'
    | '/parametres'
    | '/produits'
    | '/stocks'
    | '/ventes'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/produits/$productId'
    | '/super-admin/abonnements'
    | '/super-admin/admins'
    | '/super-admin/entreprises'
    | '/super-admin/logs'
    | '/super-admin/mfa'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confidentialite'
    | '/login'
    | '/mentions-legales'
    | '/_authenticated/caisse'
    | '/_authenticated/comptabilite'
    | '/_authenticated/conformite'
    | '/_authenticated/dashboard'
    | '/_authenticated/employes'
    | '/_authenticated/parametres'
    | '/_authenticated/produits'
    | '/_authenticated/stocks'
    | '/_authenticated/super-admin'
    | '/_authenticated/ventes'
    | '/superadmin/dashboard'
    | '/superadmin/login'
    | '/_authenticated/produits/$productId'
    | '/_authenticated/super-admin/abonnements'
    | '/_authenticated/super-admin/admins'
    | '/_authenticated/super-admin/entreprises'
    | '/_authenticated/super-admin/logs'
    | '/_authenticated/super-admin/mfa'
    | '/_authenticated/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventes': {
      id: '/_authenticated/ventes'
      path: '/ventes'
      fullPath: '/ventes'
      preLoaderRoute: typeof AuthenticatedVentesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stocks': {
      id: '/_authenticated/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof AuthenticatedStocksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produits': {
      id: '/_authenticated/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AuthenticatedProduitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employes': {
      id: '/_authenticated/employes'
      path: '/employes'
      fullPath: '/employes'
      preLoaderRoute: typeof AuthenticatedEmployesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conformite': {
      id: '/_authenticated/conformite'
      path: '/conformite'
      fullPath: '/conformite'
      preLoaderRoute: typeof AuthenticatedConformiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comptabilite': {
      id: '/_authenticated/comptabilite'
      path: '/comptabilite'
      fullPath: '/comptabilite'
      preLoaderRoute: typeof AuthenticatedComptabiliteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/caisse': {
      id: '/_authenticated/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof AuthenticatedCaisseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/': {
      id: '/_authenticated/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof AuthenticatedSuperAdminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/mfa': {
      id: '/_authenticated/super-admin/mfa'
      path: '/mfa'
      fullPath: '/super-admin/mfa'
      preLoaderRoute: typeof AuthenticatedSuperAdminMfaRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/logs': {
      id: '/_authenticated/super-admin/logs'
      path: '/logs'
      fullPath: '/super-admin/logs'
      preLoaderRoute: typeof AuthenticatedSuperAdminLogsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/entreprises': {
      id: '/_authenticated/super-admin/entreprises'
      path: '/entreprises'
      fullPath: '/super-admin/entreprises'
      preLoaderRoute: typeof AuthenticatedSuperAdminEntreprisesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/admins': {
      id: '/_authenticated/super-admin/admins'
      path: '/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof AuthenticatedSuperAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/super-admin/abonnements': {
      id: '/_authenticated/super-admin/abonnements'
      path: '/abonnements'
      fullPath: '/super-admin/abonnements'
      preLoaderRoute: typeof AuthenticatedSuperAdminAbonnementsRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRoute
    }
    '/_authenticated/produits/$productId': {
      id: '/_authenticated/produits/$productId'
      path: '/$productId'
      fullPath: '/produits/$productId'
      preLoaderRoute: typeof AuthenticatedProduitsProductIdRouteImport
      parentRoute: typeof AuthenticatedProduitsRoute
    }
  }
}

interface AuthenticatedProduitsRouteChildren {
  AuthenticatedProduitsProductIdRoute: typeof AuthenticatedProduitsProductIdRoute
}

const AuthenticatedProduitsRouteChildren: AuthenticatedProduitsRouteChildren = {
  AuthenticatedProduitsProductIdRoute: AuthenticatedProduitsProductIdRoute,
}

const AuthenticatedProduitsRouteWithChildren =
  AuthenticatedProduitsRoute._addFileChildren(
    AuthenticatedProduitsRouteChildren,
  )

interface AuthenticatedSuperAdminRouteChildren {
  AuthenticatedSuperAdminAbonnementsRoute: typeof AuthenticatedSuperAdminAbonnementsRoute
  AuthenticatedSuperAdminAdminsRoute: typeof AuthenticatedSuperAdminAdminsRoute
  AuthenticatedSuperAdminEntreprisesRoute: typeof AuthenticatedSuperAdminEntreprisesRoute
  AuthenticatedSuperAdminLogsRoute: typeof AuthenticatedSuperAdminLogsRoute
  AuthenticatedSuperAdminMfaRoute: typeof AuthenticatedSuperAdminMfaRoute
  AuthenticatedSuperAdminIndexRoute: typeof AuthenticatedSuperAdminIndexRoute
}

const AuthenticatedSuperAdminRouteChildren: AuthenticatedSuperAdminRouteChildren =
  {
    AuthenticatedSuperAdminAbonnementsRoute:
      AuthenticatedSuperAdminAbonnementsRoute,
    AuthenticatedSuperAdminAdminsRoute: AuthenticatedSuperAdminAdminsRoute,
    AuthenticatedSuperAdminEntreprisesRoute:
      AuthenticatedSuperAdminEntreprisesRoute,
    AuthenticatedSuperAdminLogsRoute: AuthenticatedSuperAdminLogsRoute,
    AuthenticatedSuperAdminMfaRoute: AuthenticatedSuperAdminMfaRoute,
    AuthenticatedSuperAdminIndexRoute: AuthenticatedSuperAdminIndexRoute,
  }

const AuthenticatedSuperAdminRouteWithChildren =
  AuthenticatedSuperAdminRoute._addFileChildren(
    AuthenticatedSuperAdminRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCaisseRoute: typeof AuthenticatedCaisseRoute
  AuthenticatedComptabiliteRoute: typeof AuthenticatedComptabiliteRoute
  AuthenticatedConformiteRoute: typeof AuthenticatedConformiteRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployesRoute: typeof AuthenticatedEmployesRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedProduitsRoute: typeof AuthenticatedProduitsRouteWithChildren
  AuthenticatedStocksRoute: typeof AuthenticatedStocksRoute
  AuthenticatedSuperAdminRoute: typeof AuthenticatedSuperAdminRouteWithChildren
  AuthenticatedVentesRoute: typeof AuthenticatedVentesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCaisseRoute: AuthenticatedCaisseRoute,
  AuthenticatedComptabiliteRoute: AuthenticatedComptabiliteRoute,
  AuthenticatedConformiteRoute: AuthenticatedConformiteRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployesRoute: AuthenticatedEmployesRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedProduitsRoute: AuthenticatedProduitsRouteWithChildren,
  AuthenticatedStocksRoute: AuthenticatedStocksRoute,
  AuthenticatedSuperAdminRoute: AuthenticatedSuperAdminRouteWithChildren,
  AuthenticatedVentesRoute: AuthenticatedVentesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
